package component.localization

enum class Strings {
    AppName,
    AppMotto,
    CompanyName,
    AppVersion,
    AppCopyright,

    NoImage,
    CloseButton,
    Apply,
    ShowMore,
    RemoveFilter,
    AddFilter,
    Logo,

    Unknown,
    Save,
    Add,

    Login,
    SignUp,
    ContinueWithGoogle,
    ContinueWithFacebook,
    Or,
    Email,
    Password,
    ForgotPassword,
    DontHaveAccount,
    SignUpWithGoogle,
    SignUpWithFacebook,
    FullName,
    RepeatPassword,
    Newsletter,
    AlreadyHaveAnAccount,
    PrivacyPolicy,
    And,
    TermsOfService,
    BySigningUpAgree,
    ForgotPasswordDescription,
    GetResetLink,
    CheckEmail,
    CheckEmailDescription,
    OpenGmail,
    OpenOutlook,
    BackTo,

    Phone,
    PersonalDetails,
    OldPassword,
    NewPassword,
    Address,
    AdditionalInformation,
    PostalCode,
    City,
    State,
    Country,

    PromoText,
    HelpAndFaq,
    Help,
    CurrencyEnUs,
    Search,
    Orders,
    Returns,
    Wishlist,
    Profile,
    Logout,

    Subscribe,
    Accessibility,
    TrackOrder,
    Shipping,
    FAQs,
    ContactUs,
    AboutUsSmall,
    AboutUs,
    Career,
    CyberSecurity,
    Press,
    DeliverTo,
    Language,
    English,
    Users,
    Dashboard,
    Stats,
    Products,
    Edit,
    Cancel,
    NewUser,
    Delete,
    ResetPassword,
    Role,
}
